### ISSUE TITLE
Azure feed exporter doesn't work

### ISSUE THREAD

**Issue by proway2** [scrapy-plugins/scrapy-feedexporter-azure-storage#1]
- Fix the exporter, so that it works out of the box (it doesn't work now).
- Fix the exporter so that it could be used with Scrapy `FEEDS` setting.
- Add support for all possible ways credentials may be provided https://docs.microsoft.com/en-us/python/api/overview/azure/storage-blob-readme?view=azure-python#types-of-credentials.
- Add `setup.py` (upload it to PyPI) so that it could be installed properly.

**Comment by imrankhan-ik** [comment]
Thanks, @proway2 . 
I created pull request #2 for that by getting help from the hotfix you made.
